### ISSUE TITLE
Cryptography

### ISSUE THREAD

**Issue by i0nsec** [holzschu/a-shell#132]
pip install cryptography fails

```

  ERROR: Command errored out with exit status 1
:
   command: /private/var/containers/Bundle/Appl
ication/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-
Shell.app/Library/bin/python3 /private/var/cont
ainers/Bundle/Application/383E7208-43ED-48F6-B6
A8-C38B26BD8E67/a-Shell.app/Library/lib/python3
.9/site-packages/pip/_vendor/pep517/_in_process
.py get_requires_for_build_wheel /private/var/m
obile/Containers/Data/Application/0B472228-0AE8
-4AFA-9846-5A33DE633DF3/tmp/tmp60v41wgr
       cwd: /private/var/mobile/Containers/Data
/Application/0B472228-0AE8-4AFA-9846-5A33DE633DF3/tmp/pip-install-xllx4drf/cryptography
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 83, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/os.py", line 682, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/bin/python3 /private/var/containers/Bundle/Application/383E7208-43ED-48F6-B6A8-C38B26BD8E67/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/0B472228-0AE8-4AFA-9846-5A33DE633DF3/tmp/tmp60v41wgr Check the logs for 
full command output.

```

**Comment by holzschu** [comment]
Isn't it already installed? What does `pip show cryptography` show?

**Comment by i0nsec** [comment]
It's not installed 

```

pip show cryptography
WARNING: Package(s) not found: cryptography

```

**Comment by holzschu** [comment]
Oh, right, my mistake, I was on the development version, not the AppStore version.
Well, that is an easy one to fix. It will be in the next version.

**Comment by i0nsec** [comment]
Sounds good
