### ISSUE TITLE
Can’t pip install alpha_vantage

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#133]
$ pip install alpha_vantage
Defaulting to user installation because normal site-packages is not writeable
Collecting alpha_vantage
  Using cached alpha_vantage-2.2.0.tar.gz (20 kB)
Collecting aiohttp
  Downloading aiohttp-3.7.3.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 5.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/bin/python3 /priva
te/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_ven
dor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/5190CF10-63B9-4B91-96D9-01E
8E7A9354B/tmp/tmpc7msk7ga
       cwd: /private/var/mobile/Containers/Data/Application/5190CF10-63B9-4B91-96D9-01E8E7A9354B/tmp/pip-install-9dxitel4/aiohttp
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 83, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/os.py", line 682, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/bin/python3 /private/var/containers/Bundle/Application/0510C216-9D53-4265-A377-3BF884E7CB5D/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Appl
ication/5190CF10-63B9-4B91-96D9-01E8E7A9354B/tmp/tmpc7msk7ga Check the logs for full command output.

**Comment by holzschu** [comment]
It makes sense: alpha-vantage tries to install aiohttp, and aiohttp cannot be installed because it has C components (see issue #130).
