### ISSUE TITLE
Using a-Shell remotely

### ISSUE THREAD

**Issue by VictorXLR** [holzschu/a-shell#158]
Hi,

I picked up this tool and i really like it but its not very nice using it from an iphone. I wanted to use it from my laptop remotely so after doing some research i realized that you could install [tmate](https://tmate.io/) from [Pip](https://pypi.org/project/tmate/).

you can install tmate from pip in a-shell but you cant connect to it from the provided ssh string from another device with the following stack trace. 

```
$ tmate
[TMateClient] Connect SSH server ssh.tmate.io:22...
    [Notify] web session read only: https://tmate.io/t/ro-NPauDJb9994j3VYdXs96726G6
[Notify] ssh session read only: ssh ro-NPauDJb9994j3VYdXs96726G6@sgp1.tmate.io
[Notify] web session: https://tmate.io/t/7ShNwEHrqrxCu8HEWUBsBVhz4
[Notify] ssh session: ssh 7ShNwEHrqrxCu8HEWUBsBVhz4@sgp1.tmate.io
[Notify] tmate can be upgraded to 2.4.0. See https://tmate.io for a list of new features
[TMateClient] Window size changed to -1, -1
[TMateClient] Window size changed to 120, 29
[Notify] A mate has joined (142.167.221.83) -- 1 client currently connected
[TMateClient] Spawn new shell (120, 29)
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/bin/tmate", line 8, in <module>
    sys.exit(main())
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/__main__.py", line 46, in main
    loop.run_until_complete(run(args.host, args.port, args.wait_timeout))
  File "/private/var/containers/Bundle/Application/B86462AB-DB2A-4BAA-AF02-26E403E51794/a-Shell.app/Library/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/__main__.py", line 16, in run
    await cli.serve(wait_timeout=wait_timeout)
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/client.py", line 240, in serve
    self.process_message_in(msg)
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/client.py", line 353, in process_message_in
    self._shell.stdin.write(buffer)
AttributeError: 'NoneType' object has no attribute 'write'
Future exception was never retrieved
future: <Future finished exception=OSError('out of pty devices')>
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/utils.py", line 119, in _wrap
    fut.set_result(await coro)
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/client.py", line 249, in spawn_shell
    proc, _, _, _ = await self._shell.create()
  File "/var/mobile/Containers/Data/Application/A505F218-611B-4178-9E66-FEA0E4AA31D3/Library/lib/python3.9/site-packages/tmate/shell.py", line 71, in create

    pid, self._fd = pty.fork()
  File "/private/var/containers/Bundle/Applicat
ion/B86462AB-DB2A-4BAA-AF02-26E403E51794/a-Shel
l.app/Library/lib/python3.9/pty.py", line 97, i
n fork
    master_fd, slave_fd = openpty()
  File "/private/var/containers/Bundle/Applicat
ion/B86462AB-DB2A-4BAA-AF02-26E403E51794/a-Shel
l.app/Library/lib/python3.9/pty.py", line 30, i
n openpty
    master_fd, slave_name = _open_terminal()
  File "/private/var/containers/Bundle/Applicat
ion/B86462AB-DB2A-4BAA-AF02-26E403E51794/a-Shel
l.app/Library/lib/python3.9/pty.py", line 60, i
n _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
```

I dont really know much about iOS, i use a windows machine and i really wanted this to work since i would be able to write more scripts on a-shell, I wanted to bring this to your attention incase there was any interest in remotely sshing into an iphone

**Comment by VictorXLR** [comment]
Also, tmate supports static builds so maybe we could have static builds of it attached with the machine, that way we can use a-shell remotely from other devices.

**Comment by holzschu** [comment]
Hi, there are no forks, no ptys, no shells and no background execution on iOS. This explains the error message you see: Python tries to launch pty.fork() and gets an error. 

These technical limitations also mean that remote execution of code would be quite limited: you would have to keep the app active, in the foreground. I would have to write a fake shell and fake ptys to communicate with tmate.

**Comment by VictorXLR** [comment]
Oh ok, thank you for the quick response, I will be closing this issue for now, feel free to reference this issue when this has been implemented. 

Happy New Year.
