### ISSUE TITLE
Cannot do `git commit` (1.6.6 Build 132)

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#169]
I tried to use the new `git` command (by Dulwich), but I couldn't do `git commit`. Does anyone have a solution?

- iPadOS 14.4 Beta 2
- a-Shell 1.6.6 Build 132 (TestFlight)

```console
$ mkdir test
$ cd test
$ git init
$ git status
$ echo foobar > a
$ git add a
$ git status
Changes to be committed:

        add: a

$ git commit -m "initial"
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/bin/git", line 36, in <module>
    sys.exit(load_entry_point('dulwich==0.20.15', 'console_scripts', 'dulwich')())
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 727, in main
    return cmd_kls().run(argv[1:])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 25
1, in run
    opts, args = getopt(args, "", ["message"])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/getopt.py", line 95, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -m not recognized
$ git commit
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/bin/git", line 36, in <module>
    sys.exit(load_entry_point('dulwich==0.20.15', 'console_scripts', 'dulwich')())
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 72
7, in main
    return cmd_kls().run(argv[1:])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 25
3, in run
    porcelain.commit(".", message=opts["--message"])
KeyError: '--message'
$ git commit --message "initial"
pre-commit: command not found
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/repo.py", line 8
64, in do_commit
    self.hooks['pre-commit'].execute()
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/hooks.py", line 
99, in execute
    raise HookError("Hook %s exited with non-zero status %d"
dulwich.errors.HookError: Hook pre-commit exited with non-zero status 127
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/bin/git", line 36, in <module>
    sys.exit(load_entry_point('dulwich==0.20.15', 'console_scripts', 'dulwich')())
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 72
7, in main
    return cmd_kls().run(argv[1:])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/cli.py", line 25
3, in run
    porcelain.commit(".", message=opts["--message"])
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/porcelain.py", l
ine 347, in commit
    return r.do_commit(
  File "/private/var/containers/Bundle/Application/B30ECD0A-1E36-4C9F-8FE0-4F03F55C848F/a-Shell.app/Library/lib/python3.9/site-packages/dulwich/repo.py", line 8
66, in do_commit
    raise CommitError(e)
dulwich.errors.CommitError: Hook pre-commit exited with non-zero status 127
```

**Comment by holzschu** [comment]
Thanks for signaling this. I can reproduce the issue. I’m going to track it down.

**Comment by kkk669** [comment]
Dulwich's `git` has been removed, so I close this issue.
