### ISSUE TITLE
Feature request: venv (Python)

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#193]
## Motivation

Currently, `pip` installs all packages into `$PYTHONUSERBASE/lib/python3.9/site-packages` on a-Shell.

However, I often want to install some packages without modifying `$PYTHONUSERBASE/lib/python3.9/site-packages`. For example:

- when I want to install dependencies of some package from `requirements.txt`
- when I need to install a different version of a package than the one currently installed in `$PYTHONUSERBASE/lib/python3.9/site-packages`
- when I want to use some package temporarily

Generally speaking, most people use `venv` in these cases. So, I tried it as follows, but the error occurred in `ensurepip`.

```console
$ mkdir pytest
$ cd pytest
$ python -m venv venv
Error: Command '['/private/var/mobile/Containers/Data/Application/6BCBA8F3-554D-46A0-AF29-D9300A73ECD7/Docume
nts/pytest/venv/bin/python3_ios', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit s
tatus 127.
$ ls venv/bin
python          python3         python3.9       python3_ios
$ tree venv
venv
├── bin [error opening dir]
├── include
├── lib
│   └── python3.9
│       └── site-packages
└── pyvenv.cfg
5 directories, 1 file
$ python -Im ensurepip --upgrade --default-pip
  File "<string>", line 6
    runpy.run_module(
                     ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/ensurepip/__init__.py", line 210, in _main
    return _bootstrap(
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/ensurepip/__init__.py", line 129, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/ensurepip/__init__.py", line 38, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/containers/Bundle/Application/8761C36B-55DD-496D-8BD4-A20C76656F9E/a-Shell.app/Library/bin/python3', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/private/var/
mobile/Containers/Data/Application/6BCBA8F3-554D-46A0-AF29-D9300A73ECD7/tmp/tmpexfv1gi8/setuptools-49.2.1-py3-none-any.whl\', \'/private/var/mobile/Containers/Data/Application/6BCBA8F3-554D-46A0-AF29-D9300A73ECD7/tmp/tmpexfv1gi8/pip-20.2.3-py2.py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/private/var/mobile/Containers/Data/Application/6BCBA8F3-554D-46A0-AF29-D9300A73ECD7/tmp/tmpexfv1gi8\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
```

**Comment by holzschu** [comment]
Hi, build 211 (currently on TestFlight: https://testflight.apple.com/join/WUdKe3f4 ) has virtual environments working for Python. It's not exactly the same as `venv`: only user-installed packages are in the virtual environment, system packages are shared between all environments.

Syntax is the usual: `python -m venv .venv`, followed by `source .venv/bin/activate` to activate the new environment, `deactivate` to deactivate the environment.
