### ISSUE TITLE
Pip doesn’t work on latest IPadOS

### ISSUE THREAD

**Issue by xinity** [holzschu/a-shell#323]
Hello,

Trying a-Shell on my iPad Pro using latest stable IPadOS 15 release, pip doesn’t work and i can’t explain why :(
Here’s the output of the single  `pip` command : 
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9,
 in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py
", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", 
line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", l
ine 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/cli/parser.py", line 
12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/configuration.py", li
ne 21, in <module>
    from pip._internal.exceptions import (
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_internal/exceptions.py", line 
7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.
py", line 36, in <module>
    import email.parser
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/email/utils.py", line 28, in <module>
    import random
  File "/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/random.py", line 64, in <module>
    from hashlib import sha512 as _sha512
ImportError: cannot import name 'sha512' from 'hashlib' (/private/var/containers/Bundle/Application/5CCB83C0-8BAB-46B8-A589-901EB184E169/a-Shell.app/Library/lib/python3.9/
hashlib.py)
```
Any ideas ?

**Comment by holzschu** [comment]
Hi, 
Thanks for reaching out. I tried pip on a random package, and I did not get this issue.

There are multiple possibilities here: 
- it could be that I fixed the issue by inadvertance, without realizing it. If that's the case, it will be fixed if you use the latest TestFlight version: https://testflight.apple.com/join/WUdKe3f4
- it could be that the package you try to install requires more than two levels of python (pip runs in one python interpreter, and often calls "python setup.py", so that's two python running at the same time, which is the maximum for a-Shell; Carnets has a higher limit).
- it could be that the package you try to install requires access to parts of the Python install that import sha512, and the one I tried does not. 

Which package were you trying to install?
