### ISSUE TITLE
cannot use sr() or sr1()?

### ISSUE THREAD

**Issue by Luckytrang2010** [holzschu/a-shell#381]
![image](https://user-images.githubusercontent.com/53712708/154078953-976c3c90-e045-4057-b9c0-253a2c7be599.png)

Full error message:

```
File "/private/var/containers/Bundle/Application
/157DC282-BD7F-46CD-A6E3-AB7E569AC65F/a-Shell.app/Library/lib/python3.9/site-packages/IPython/core/history.py", line 219, in __init__
    self.init_db()
  File "/private/var/containers/Bundle/Application/157DC282-BD7F-46CD-A6E3-AB7E569AC65F/a-Shell.app/Library/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/private/var/containers/Bundle/Application/157DC282-BD7F-46CD-A6E3-AB7E569AC65F/a-Shell.app/Library/lib/python3.9/site-packages/IPython/core/history.py", line 85, in catch_corrupt_db
    elif self.hist_file.is_file():
AttributeError: 'str' object has no attribute 'is_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/157DC282-BD7F-46CD-A6E3-AB7E569AC65F/a-Shell.app/Library/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/var/mobile/Containers/Data/Application/AF7C9F40-660E-4DB2-97B9-42941CC25907/Library/lib/python3.9/site-packages/scapy/sendrecv.py", line 609, in sr
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/var/mobile/Containers/Data/Application/AF7C9F40-660E-4DB2-97B9-42941CC25907/Library/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 254, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/var/mobile/Containers/Data/Application/AF
7C9F40-660E-4DB2-97B9-42941CC25907/Library/lib/pyt
hon3.9/site-packages/scapy/arch/bpf/supersocket.py
", line 62, in __init__
    (self.ins, self.dev_bpf) = get_dev_bpf()
  File "/var/mobile/Containers/Data/Application/AF
7C9F40-660E-4DB2-97B9-42941CC25907/Library/lib/pyt
hon3.9/site-packages/scapy/arch/bpf/core.py", line
 146, in get_dev_bpf
    raise Scapy_Exception("No /dev/bpf handle is a
vailable !")
scapy.error.Scapy_Exception: No /dev/bpf handle is
 available !
If you suspect this is an IPython 8.0.1 bug, pleas
e report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-de
v@python.org
You can print a more detailed traceback right now 
with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purpos
es can be enabled via:
    c.Application.verbose_crash=True
```

Is there any workaround for sending and receiving packets? Is this incompatible?

**Comment by Luckytrang2010** [comment]
iOS is so strict in privileges. Thank you though for letting me know 😊
