### ISSUE TITLE
Python cannot import bundled NumPy

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#5]
Environment:

- a-Shell 1.0 (34) on iPadOS 13.2 Developer Beta 3 (17B5077a)
- a-Shell 1.0 (34) on iOS 13.1.3

Log:

```
$ python
Python 3.7.1 (default, Oct  4 2019, 14:40:06) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/_multiarray_umath.py", line 7, in <module>
    __bootstrap__()

  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/_multiarray_umath.py", line 7, in <module>
    __bootstrap__()
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/_multiarray_umath.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/private/var/containers/Bundle/Application/B178CEC6-6A18-4407-9E93-AB9E0D44B4D7/a-Shell.app/Frameworks/python-numpy.core._multiarray_umath.framework/python-numpy.core._multiarray_umath, 0x0002): dlopen(): file not found: /private/var/containers/Bundle/Application/B178CEC6-6A18-4407-9E93-AB9E0D44B4D7/a-Shell.app/Frameworks/python-numpy.core._multiarray_umath.framework/python-numpy.core._multiarray_umath

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/lib/python3.7/site-packages/numpy-1.16.0-py3.7-macosx-10.9-x86_64.egg/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /var/mobile/Containers/Data/Application/F7637F3E-E1F4-4D40-8BDF-9A865B244EC8/Library/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dlopen(/private/var/containers/Bundle/Application/B178CEC6-6A18-4407-9E93-AB9E0D44B4D7/a-Shell.app/Frameworks/python-numpy.core._multiarray_umath.framework/python-numpy.core._multiarray_umath, 0x0002): dlopen(): file not found: /private/var/containers/Bundle/Application/B178CEC6-6A18-4407-9E93-AB9E0D44B4D7/a-Shell.app/Frameworks/python-numpy.core._multiarray_umath.framework/python-numpy.core._multiarray_umath

>>> 
```

**Comment by holzschu** [comment]
Hi, 
Thanks for signaling this; I'm going to have a look. In the meantime, it works in ipython.
(which is puzzling, because they should be identical at that level).

**Comment by kkk669** [comment]
I didn't realize it, but it certainly works on ipython.

**Comment by kkk669** [comment]
Thanks for releasing a new build via TestFlight. I confirmed that it was fixed.

**Comment by holzschu** [comment]
There are so many things not fixed in the latest TestFlight release, I almost did not release it. I'm glad I could close this specific issue.
