### ISSUE TITLE
Pynput library not working

### ISSUE THREAD

**Issue by Emasoft** [holzschu/a-shell#549]
The python Pynput library doesn't seem to be working. It gives me the following error:

```shell
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/C3A8D358-6FA8-44AC-9596-9D28037DD043/Library/lib/python3.11/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/var/mobile/Containers/Data/Application/C3A8D358-6FA8-44AC-9596-9D28037DD043/Library/lib/python3.11/site-packages/pynput/keyboard/__init__.py", line 31, in <module
>
    backend = backend(__name__)
              ^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/C3A8D358-6FA8-44AC-9596-9D28037DD043/Library/lib/python3.11/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: dlopen(/private/var/containers/Bundle/Application/5F45CB59-DDDA-4BC3-B23C-D09F805B1FF8/a-Shell.app/Frameworks/python3_ios-objc
._objc.framework/python3_ios-objc._objc, 0x0002): tried: '/private/var/containers/Bundle/Application/5F45CB59-DDDA-4BC3-B23C-D09F805B1FF8/a-Shell.app/Frameworks/python3_io
s-objc._objc.framework/python3_ios-objc._objc' (errno=2), '/private/preboot/Cryptexes/OS/private/var/containers/Bundle/Application/5F45CB59-DDDA-4BC3-B23C-D09F805B1FF8/a-S
hell.app/Frameworks/python3_ios-objc._objc.framework/python3_ios-objc._objc' (errno=2), '/private/var/containers/Bundle/Application/5F45CB59-DDDA-4BC3-B23C-D09F805B1FF8/a-
Shell.app/Frameworks/python3_ios-objc._objc.framework/python3_ios-objc._objc' (errno=2), '/System/Library/Frameworks/python3_ios-objc._objc.framework/python3_ios-objc._obj
c' (errno=2, not in dyld cache)
Try one of the following resolutions:
 * Please make sure that you have Python bindings for the system frameworks installed
```

**Comment by holzschu** [comment]
That makes sense: pynput is trying to detect the architecture, to see if it's one of the architectures it supports (darwin, win32, linux, see: https://pynput.readthedocs.io/en/latest/ ) and concludes that it isn't, hence the message "this platform is not supported".

Making pynput work with an iPad would probably require a full rewrite: the keyboard and the mouse work very differently on an iPad than they do on OSX or Windows.
