### ISSUE TITLE
pip install openai[embeddings] causes ImportError: scipy is not installed

### ISSUE THREAD

**Issue by Emasoft** [holzschu/a-shell#577]
It seems that installing openai with the embeddings requires scipy:

```
[~Documents]$ pip install openai[embeddings]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[embeddings] in /var/mobile/Containers/Data/Application/15F63F1A-A877-45D7-BF92-21128A4CBB96/Library/lib/python3.11/site-packages (0.27.0)
Requirement already satisfied: requests>=2.20 in /private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/site-packages (from openai[embeddings]) (2.28.1)
Requirement already satisfied: tqdm in /private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/site-packages (from openai[embeddings]) (4.64.1)
Requirement already satisfied: aiohttp in /var/mobile/Containers/Data/Application/15F63F1A-A877-45D7-BF92-21128A4CBB96/Library/lib/python3.11/site-packages (from openai[embeddings]) (3.8.3)
Collecting scikit-learn>=1.0.2
  Using cached scikit-learn-1.2.1.tar.gz (7.3 MB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "<string>", line 218, in check_package_status
        File "/private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'scipy'
      Traceback (most recent call last):
        File "/var/mobile/Containers/Data/Application/15F63F1A-A877-45D7-BF92-21128A4CBB96/Library/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/mobile/Containers/Data/Application/15F63F1A-A877-45D7-BF92-21128A4CBB96/Library/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/mobile/Containers/Data/Application/15F63F1A-A877-45D7-BF92-21128A4CBB96/Library/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/containers/Bundle/Application/E45712A9-5A86-4C96-AFA6-89269617F403/a-Shell.app/Library/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 669, in <module>
        File "<string>", line 660, in setup_package
        File "<string>", line 245, in check_package_status
      ImportError: scipy is not installed.
      scikit-learn requires scipy >= 1.3.2.
      Installation instructions are available on the scikit-learn website: http://scikit-learn.org/st
able/install.html
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[~Documents]$ 
```

**Comment by holzschu** [comment]
More than that, it also requires scikit-learn. Both are implemented in "Carnets-with-Scipy".

**Comment by Emasoft** [comment]
@holzschu I have Carnets-with-Scipy installed, but it doesn't see the lib from a-Shell. Is there a way to install those 2 in a-Shell?

**Comment by holzschu** [comment]
No, you cannot share binaries, including dynamic libraries, between apps.

**Comment by Emasoft** [comment]
@holzschu Can you integrate SciPy in a-Shell?

**Comment by holzschu** [comment]
Technically, yes. 
In practice, I am worried about the increase in size for an app that is already more than 1 GB. It could carry it well over 2 GB. I routinely have issues related to size and number of embedded frameworks with Carnets-with-Scipy.

**Comment by Emasoft** [comment]
@holzschu I don't see it as an issue at all. I regulary download games about 5GB or more. But if you are worried, just make the package optional and add it as a In-App Purchase.

**Comment by holzschu** [comment]
You cannot have binaries (including dynamic libraries) in an In-App purchase. Otherwise I would already be doing it.

**Comment by Emasoft** [comment]
@holzschu I see. Well, the size is still not an issue. Moreover, you already created a mini version of a-Shell for users concerned with space. Those who download the full version are already aware of the bigger size and willing to pay such price for more important packages like SciPy.

**Comment by Emasoft** [comment]
@holzschu Besides, the whole programming world is about ChatGPT and OpenAI now. And the trend is growing as more and more applications of their AI models are invented and used in javascript or python scripts. I suspect that very soon not being able to install the OpenAI libraries would be seen as a serious shortcoming of a-Shell.

**Comment by augustobob** [comment]
![CC5A6EC3-DB28-4F3A-A0CA-4BBFB4F8FB0E](https://user-images.githubusercontent.com/41238825/228917495-843e7e6a-9358-41a2-9f1b-e1016ca8b703.jpeg)

**Comment by holzschu** [comment]
That would be great, but it wouldn't actually work: you cannot have binaries inside the extensions that are loaded after the app is installed. For TeX and LuaTeX, we only install the text files of the texlive installation, the binaries are already present in the main app.
