### ISSUE TITLE
BUG: a-Shell causes errors when a web request is made while the app is in background

### ISSUE THREAD

**Issue by Emasoft** [holzschu/a-shell#623]
a-Shell causes errors when a web request is made while the app is in background.
This is an example error using the Dropbox official python script to upload files:

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Data/Application/E80C2799-69DB-4A65-B18C-5CF286BF5E33/Documents/Downloads/dropbox_upload.py", line 699, in upload_file
    dbx.files_upload_session_append_v2(f.read(self.chunk), cursor)
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/dropbox/base.py", line 3257, in files_upload_session_append_v2
    r = self.request(
        ^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 326, in request
    res = self.request_json_string_with_retry(host,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_retry
    return self.request_json_string(host,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 589, in request_json_string
    r = self._session.post(url,
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/pyth
on3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/B2793D14-9179-4631-AC2A-8F6861004E83/Library/lib/pyth
on3.11/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError('The write operation timed 
out'))
```

If a-Shell is not sent in background, but stays in foreground, no error occurs.

**Comment by Emasoft** [comment]
I checked while a-Shell is in background, and the connection is working. Browsing, streaming web radio, google maps, etc. All these are working fine. Even other apps running in background at the same time as a-Shell work fine (I started a batch copy with FilebrowserGO, and it worked while in background till its completition with no errors). It is only a-Shell that has trouble accessing the web while in background.
