### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#67]
I tried to install prettytable and got errors.
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Fatal Python error: _Py_InitializeCore_impl: no thread state found
Is it affect possible to install Pure python modules using PIP?

**Comment by holzschu** [comment]
I tried to reproduce the issue; there is no issue for me with "pip install prettytable".

**Comment by ifuchs** [comment]
I also cannot reproduce the error. However I just tried another install, pip install alpha_vantage and got:
‘’’
wheel'.
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/bin/python3 /var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/tmp/tmpwgvs1u2d
       cwd: /private/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/tmp/pip-install-xuaybek2/multidict
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_ve
ndor/pep517/_in_process.py", line 83, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
    File "/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/os.py", line 680, in 
__getitem__
      raise KeyError(key) from None
  KeyError: 'PEP517_BUILD_BACKEND'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Librar
y/bin/python3 /var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip
/_vendor/pep517/_in_process.py get_requires_for_build_wheel /private/var/mobile/Containers/Data/Application/51BC2865-1CF1-4AD9-AF2
E-87F2BCE1DD7E/tmp/tmpwgvs1u2d Check the logs for full command output.
‘’’

**Comment by holzschu** [comment]
I can reproduce this one. Looking at the warning message a few lines above, the problem is that multidict requires a C compiler. a-Shell does have a C compiler, but creating a dynamic library for a module is still a few steps in the future...

**Comment by ifuchs** [comment]
This  Is odd since Pythonista has the same restrictions (unless this
particular module was bundled) and I was able to do the install. Also ,
Pyto and Carnets completed the install.

**Comment by ifuchs** [comment]
I just ran pip install and got:
`ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/var/mobile/Containers/Data/Application/51BC2865-1CF1-
4AD9-AF2E-87F2BCE1DD7E/Library/lib/python3.7/site-packages/pip/_internal/index/__init__.py) `

**Comment by holzschu** [comment]
For alpha_vantage, you can install it if you go to the previous version using `pip install alpha_vantage==2.1.3`.

**Comment by ifuchs** [comment]
pip install alpha_vantage==2.1.3. Collecting alpha_vantage==2.1.3.
Downloading
https://files.pythonhosted.org/packages/c9/72/c3a2a8371f94515a2f0b1203dc152cf8d82dc17baeea0c1af5a23d10eca7/alpha_vantage-2.1.3.tar.gz
ERROR: Complete output from command python setup.py egg_info: ERROR:
segmentation fault ----------------------------------------ERROR: Command
"python setup.py egg_info" failed with error code 1 in
/private/var/mobile/Containers/Data/Application/DD76B14A-87B2-4531-A128
-A6C6A88F505E/tmp/pip-install-u2to9h4x/alpha-vantage/

**Comment by ifuchs** [comment]
At this point just entering pip gives an error with traceback ending with:

ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/var/mobile/Containers/Data/Application/0990BD41-8610-
4C71-8AC4-0BEA2A5A41F7/Library/lib/python3.7/site-packages/pip/_internal/index/__init__.py)
