### ISSUE TITLE
Bookmarks not working in Python script

### ISSUE THREAD

**Issue by cmyplay** [holzschu/a-shell#793]
I'm trying to use the following Python script to sync two different directories.
The source  is a local folder (On My iPhone), the destination is an app folder on iCloud (technically Resilio Sync).

```
from dirsync import sync

sync("~RBackups", "~OBackups", "sync")
```

I get the following error:

 ```
Traceback (most recent call last):
  File "/private/var/mobile/Library/Mobile Documents/iCloud~is~workflow~my~workflows/Documents/Synchron/synchron.py", line 3, in <module>
    sync("~RBackups", "~OBackups", "sync")
  File "/var/mobile/Containers/Data/Application/CBAF2231-285D-4486-982C-81681F954B5B/Library/lib/python3.11/site-packages/dirsync/run.py", line 15, in sync
    copier = Syncer(sourcedir, targetdir, action, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/CBAF2231-285D-4486-982C-81681F954B5B/Library/lib/python3.11/site-packages/dirsync/syncer.py", line 107, in __init__
    raise ValueError("Error: Source directory does not exist.")
ValueError: Error: Source directory does not exist.
```

How do I address  file paths in two different sections of the system?

**Comment by holzschu** [comment]
Yes, Python has its own module for path extension, which i didn't dare touch. The issue applies to everywhere Python has access to a path, so `os.chdir("~RBackups")` will also fail.

I see several tools to fix this in the short term: 
- `os.path.realpath(__file__)`, which will tell you in which directory the current Python script is, 
- `subprocess.check_output("showmarks OBackups")` and a bit of string editing.
